### ISSUE TITLE
[Concern] Manually parsing JSON:API formatted responses

### ISSUE THREAD

**Issue by minhnimble** [Johnsonmaung/NimbleTechnicalTest_Android#13]
## Issue
For the data layer, I noticed that you are parsing JSON:API formatted responses manually instead of using a 3rd-party library for handling this task. Why do you think parsing manually like this would be a better choice? And do you think using a dedicated JSON:API parser library would add more benefits? 
https://github.com/Johnsonmaung/NimbleTechnicalTest_Android/blob/f44989bb1d294fa2f75da8e0b2ee0befe7823247/features/home/src/main/java/com/nyinyaraung/home/data/model/SurveyPagingListResponse.kt#L9-L49

Just In case you don't know what JSON:API format is and why we [recommend to use it](https://github.com/nimblehq/nimble-survey-web/wiki/REST-API), please feel free to take a look at [this](https://jsonapi.org/) for more information 🙏.

**Comment by Johnsonmaung** [comment]
Hello Mike @minhnimble ,

While I haven't yet had the opportunity to work with JSON:API in a production environment, my experience with testing open APIs using JSON:API suggests its potential. My usual approach in these cases was to leverage libraries like Gson and Moshi, similar to how I handle custom-formatted request/response structures in REST APIs.

I appreciate your recommendation to explore third-party libraries for JSON:API. I recognize the value these libraries offer in unlocking the full potential of JSON:API, such as enabling dynamic request/response capabilities and streamlining error handling. I'm interested in learning more about your preferred libraries and how they can enhance my JSON:API development experience. I will create a PR after I update with third-party libraries.

Thank you 🙏

**Comment by Johnsonmaung** [comment]
Hello Mike @minhnimble ,
I update json:api response parsing using 3rd party library **JsonApiX**.
Pls help to review in this PR #18 .
Thanks 🙏
