### ISSUE TITLE
[Improvement] Multiple build variants handling

### ISSUE THREAD

**Issue by minhnimble** [Johnsonmaung/NimbleTechnicalTest_Android#14]
## Issue
As per our our API [documentation](https://github.com/nimblehq/nimble-survey-web/wiki/REST-API#android), there are more environments that our API should be able to support, which are Staging and Production, and you only handled the Production environment so far in the build config.

https://github.com/Johnsonmaung/NimbleTechnicalTest_Android/blob/f44989bb1d294fa2f75da8e0b2ee0befe7823247/data/network/build.gradle.kts#L20-L24

As a result, It would be nice to see how you would handling different build variants in an Android project.

**Notice**: Since our Staging environment is currently offline, the focus is more on how you handle different build variants in the project, and there's no need to worry about testing on Staging.

**Comment by Johnsonmaung** [comment]
Hello Mike @minhnimble , 
I implemented flavor for other modules.
Pls help to review PR, #15
Thank you. 🙏
